spring:
  data:
    redis:
      database: 0
      host: 192.168.23.200
      port: 6379
      password: infini_rag_flow
      timeout: 5s
      connect-timeout: 5s
      lettuce:
        pool:
          max-active: 200 # 最大连接数
          max-idle: 10 # 最大连接数
          max-wait: -1ms # 最大等待时间
          min-idle: 0 # 最小空闲连接数